### ISSUE TITLE
Project manager isn't loading

### ISSUE THREAD

**Issue by Flowgram** [randy3k/Project-Manager#20]
Hi, 

Project Manager was working fine yesterday but today whenever I try to load it (Ctrl + Alt + P) I'm getting this error in the console:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 526, in run_
    return self.run()
  File "pm in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\Project Manager.sublime-package", line 304, in run
  File "pm in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\Project Manager.sublime-package", line 84, in __init__
  File "pm in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\Project Manager.sublime-package", line 102, in get_projects_info
  File "./ntpath.py", line 615, in relpath
  File "./ntpath.py", line 534, in normpath
AttributeError: 'NoneType' object has no attribute 'startswith'

I've not knowing changed anything and I'm on Sublime Text 3 Build 3065, Windows 7.

**Comment by randy3k** [comment]
Please update to the latest version. I believe that you are not using the latest version.

**Comment by Flowgram** [comment]
Hey Randy, 

I'm using version 0.5.2 which looks like the latest.

I thinking of trying an uninstall and reinstall, but will lose all the saved projects etc?

Thanks

**Comment by randy3k** [comment]
0.5.2 is the latest version. Does the problem still persist? If you have the latest version, you shouldn't have the above error message.

**Comment by Flowgram** [comment]
Yes, problem still persists, I have the latest version. I've also tried uninstalling and reinstalling via the package manager.

**Comment by randy3k** [comment]
Could you check again the console for the error? In the latest version, it should be another error

**Comment by Flowgram** [comment]
I'm on a different computer now but my Sublime settings and packages are synced. Still the same error:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 526, in run_
    return self.run()
  File "pm in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\Project Manager.sublime-package", line 310, in run
  File "pm in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\Project Manager.sublime-package", line 84, in __init__
  File "pm in C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\Project Manager.sublime-package", line 108, in get_projects_info
  File "./ntpath.py", line 615, in relpath
  File "./ntpath.py", line 534, in normpath
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by randy3k** [comment]
I have no problem of running it on a Windows machine. I suspect that there is something with the file `C:\Users\xxx\AppData\Roaming\Sublime Text 3\Installed Packages\Project Manager.sublime-package`.

You may want to remove it and perhaps, also remove the folder `C:\Users\xxx\AppData\Roaming\Sublime Text 3\Packages\Project Manager\` if it exists.

**Comment by Flowgram** [comment]
The Project Manager.sublime-package file gets removed when you uninstall the package (which I just tried again). Also folder you mention doesn't exist.

**Comment by randy3k** [comment]
I think I hv figured it out. It should be fixed by version 0.5.3.

**Comment by Flowgram** [comment]
Amazing, that worked. Thanks so much Randy!

**Comment by randy3k** [comment]
Great. Thanks for the report.
